config/routes.rb
Rails.application.routes.draw do

    root 'home#index'

  get "makes" => "makes#index"
  get "make"  => "makes#show"

  get "model_years"  => "model_years#index"
  get "model_year"   => "model_years#show"
  get "style_detail" => "model_years#details"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :condition

  def condition
    if params[:type].present?
      session[:condition] = params[:type]
    else
      unless session[:condition].present?
        session[:condition] = "NEW"
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @types = ["NEW", "USED", "ALL"]
    render json: @types
  end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController

  def index
    if session[:condition] == "ALL"
      @makes = Edmunds::Make.new.find_all
      render json: @makes
    elsif session[:condition] == "USED"
      @makes = Edmunds::Make.new.find_used_makes
      render json: @makes
    else
      @makes = Edmunds::Make.new.find_new_makes
      render json: @makes
    end
  end

  def show
    @make = params[:name]
    render json: @make
    if session[:condition] == "ALL"
      @models = Edmunds::Model.new.find_by_make_id(params[:id])
      render json: @models
    elsif session[:condition] == "USED"
      @models = Edmunds::Model.new.find_used_models_by_make_id(params[:id])
      render json: @models
    else
      @models = Edmunds::Model.new.find_new_models_by_make_id(params[:id])
      
    end
  end

end

app/controllers/model_years_controller.rb
class ModelYearsController < ApplicationController
  
  def index
    @make = params["make"]
    @model = params["model"]
    if session[:condition] == "ALL"
      @model_years = Edmunds::ModelYear.new.for_model_id(params[:id])
      render json: @model_years
    elsif session[:condition] == "USED"
      @model_years = Edmunds::ModelYear.new.find_used_model_years_by_model_id(params[:id])
      render json: @model_years
    else
      @model_years = Edmunds::ModelYear.new.find_new_model_years_by_model_id(params[:id])
      render json: @model_years
    end
  end

  def show
    @styles = Edmunds::Style.new.find_styles_by_model_year_id(params[:id])
    render json: @styles
    @model_id = @styles.first["modelId"]
    @make_id = @styles.first["makeId"]
    @year = @styles.first["year"]
    @make = @styles.first["makeName"]
    @model = @styles.first["modelName"]

  end

  def details
    @style_id = params[:id]
    @style = Edmunds::Style.new.find_by_id(@style_id)
    render json: @style
    @engine = Edmunds::Equipment.new.find_engines_by_style_id(@style_id)
    render json: @engine
    @model_id = @style.first["modelId"]
    @make_id = @style.first["makeId"]
    @year = @style.first["year"]
    @make = @style.first["makeName"]
    @model = @style.first["modelName"]
    @model_year_id = @style.first["modelYearId"]
    @style_name = @style.first["attributeGroups"]["MAIN"]["attributes"]["NAME"]["value"]
    @images = Edmunds::Photo.new.find_by_style_id(@style_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/model_years_helper.rb
module ModelYearsHelper

  def get_sample_image_for_style(style)
    get_image(style)
  end

  def get_sample_image_for_model(model)
    if model["publicationStates"].include?("NEW")
      condition = "NEW"
    elsif model["publicationStates"].include?("PRE_PROD")
      condition = "PRE_PROD"
    elsif model["publicationStates"].include?("NEW_USED")
      condition = "NEW_USED"
    else
      condition = "USED"
    end
    style = model["subModels"][condition].first["styleIds"]
    get_image(style)
  rescue
    style = model["subModels"].first.last.first["styleIds"]
    get_image(style)
  end

  def get_image(style)
    image = Edmunds::Photo.new.find_sample_by_style_id(style)
    image.match(/http/)
    image
  rescue
    "/no-image.jpg"
  end

  def find_best_image(urls)
    "http://media.ed.edmunds-media.com" + urls.select{|s| s.match(/\d{3}(.jpg)/) }.max
  end

  def style_name(style)
    "#{style["attributeGroups"]["STYLE_INFO"]["attributes"]["STANDARD_VEHICLE_DESCRIPTION"]["value"]} #{horsepower(style)} #{mpg(style)}"
  end

  def mpg(style)
    attributes = style["attributeGroups"]["SPECIFICATIONS"]["attributes"]
    "- #{attributes["EPA_CITY_MPG"]["value"]}/#{attributes["EPA_HIGHWAY_MPG"]["value"]} mpg"
  rescue
    ""
  end

  def horsepower(style)
    engine_specs = Edmunds::Equipment.new.find_engines_by_style_id(style["id"])
    "#{engine_specs.first.last["attributeGroups"]["ENGINE"]["attributes"]["HORSEPOWER"]["value"]}HP"
  rescue
    ""
  end

  def engine_highlights(engine)
    stats = engine.first.last["attributeGroups"]["ENGINE"]["attributes"]
    engine_stats = "#{stats["SIZE"]["value"]}L #{stats["HORSEPOWER"]["value"]}HP #{stats["ENGINE_CONFIGURATION"]["value"]} #{stats["CYLINDER"]["value"]}"
    "Engine Highlights: #{engine_stats}"
  rescue
    ""
  end

end

app/views/home/index.html.erb
<h3>Select Type:</h3>
<hr/>
<div class="row">
  <% @types.each do |type| %>
    <div class="large-4 columns">
      <%= link_to type, makes_path(type: type), :class => "button large expand" %>
    </div>
  <% end %>
</div>

app/views/layouts/_menu.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="top-bar">
      <ul class="title-area">
        <li class="toggle-topbar">
          <a>
            <span>
              Menu
            </span>
          </a>
        </li>
        <li class="name"></li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <li>
            <a class="active" href="<%= root_path %>">
              <span style="font-size: 1.2em;">SUREUP</span>
            </a>
          </li>
        </ul>
        <ul class="right">
          <li>
            <a class="active" href="<%= makes_path %>">
              All Makes
            </a>
          </li>
        </ul>
      </section>
    </div>
  </div>
</div>

app/views/layouts/_nav_buttons.html.erb
<div class="row">
  <div class="large-6 columns">
    <%= link_to "Home", root_path, :class => "button large secondary expand" %>
  </div>
  <div class="large-6 columns">
    <%= link_to "Back", :back, :class => "button large secondary expand" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SURE-UP</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="row">
    <div class="large-12 columns">
      <%= render 'layouts/menu' %>
      <%= render 'layouts/nav_buttons' %>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/makes/index.html.erb
<div class="container">
  <h3>
    Makes
    >
    <%= session[:condition].titleize %>
  </h3>
</div>
<div class="row">
  <% @makes.each do |make| %>
    <div class="large-4 columns">
      <%= link_to make["name"], make_path(name: make["name"], id: make["id"]), :class => "button large expand loading" %>
    </div>
  <% end %>
</div>
<div class="reveal-modal" id="loading">
  <center>
    <h4>Loading content</h4>
  </center>
  <center>
    <%= image_tag("loading.gif") %>
  </center>
</div>
<script>
  
  $(".loading").click(function(){
    $('#loading').foundation('reveal', 'open'); 
  });


</script>

app/views/makes/show.html.erb
<div class="container">
  <h3>
    <%= link_to session[:condition].titleize, root_path %>
    <%= ":" %>
    <%= link_to "Makes", makes_path %>
    >
    <%= @make %>
    >
    <%= "Models" %>
  </h3>
</div>
<hr/>
<div class="row">
  <% @models.sort{|x,y| x["name"] <=> y["name"] }.each do |model| %>
    <div class="large-4 columns">
      <div class="block">
        <%= link_to model["name"], model_years_path(make: @make, model: model["name"], id: model["id"]), :class => "button large expand" %>
        <%= image_tag(get_sample_image_for_model(model), :class => "sample_image") %>
      </div>
    </div>
  <% end %>
</div>

app/views/model_years/details.html.erb
<div class="container">
  <h3>
    <%= link_to session[:condition].titleize, root_path %>
    <%= ":" %>
    <%= link_to "Makes", makes_path %>
    >
    <%= link_to @make, make_path(name: @make, id: @make_id) %>
    >
    <%= link_to @model, model_years_path(make: @make, model: @model, id: @model_id) %>
    >
    <%= link_to @year, model_year_path(id: @model_year_id) %>
    >
    <%= @style_name %>
  </h3>
</div>
<div class="row">
  <div class="large-12 columns">
    <ul data-options="timer_speed: 8000;">
      <% @images.each do |image| %>
        <li>
          <center>
            <%= image_tag(find_best_image(image["photoSrcs"])) %>
          </center>
          <div class="orbit-caption">
            <%= image["captionTranscript"] %>
          </div>
        </li>
      <% end %>
    </ul>
    <script>
      
      $(document).foundation('orbit');


    </script>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <table>
      <thead>
        <tr>
          <th colspan="2">
            <h4>Engine Specs</h4>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @engine.first.last["attributeGroups"]["ENGINE"]["attributes"].each do |attr| %>
          <tr>
            <td>
              <%= attr.last["name"].humanize %>
            </td>
            <td>
              <%= attr.last["value"] %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <h4>Features</h4>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <div class="row">
      <% @style.first["attributeGroups"].map{|s| s[0] }.sort{|x,y| x <=> y }.each do |group| %>
        <div class="large-3 small-12 columns">
          <%= link_to group.humanize, "##{group}", :class => "button small expand" %>
        </div>
      <% end %>
    </div>
    <% @style.first["attributeGroups"].each do |attr_group| %>
      <table id="<%= attr_group[0] %>">
        <thead>
          <tr>
            <th colspan="2">
              <h4>
                <%= attr_group.last["name"].humanize %>
                <%= link_to "(Top)", "#", :style => "color: lightblue; margin-left: 10px;" %>
              </h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <% if attr_group.last["attributes"] %>
            <tr>
              <% attr_group.last["attributes"].each do |attr| %>
                <tr>
                  <td>
                    <h6>
                      <%= attr.last["name"].gsub(/_/," ") %>
                    </h6>
                  </td>
                  <td>
                    <% if attr.last["value"] %>
                      <%= attr.last["value"] %>
                    <% else %>
                      <%= "n/a" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/model_years/index.html.erb
<div class="container">
  <h3>
    <%= link_to session[:condition].titleize, root_path %>
    <%= ":" %>
    <%= link_to "Makes", makes_path %>
    >
    <%= link_to @make, make_path(name: @make, id: @model_years.first["makeId"]) %>
    >
    <%= @model %>
    >
    <%= "Model Years" %>
  </h3>
</div>
<hr/>
<div class="row">
  <% @model_years.sort{|x,y| y["year"] <=> x["year"] }.each do |year| %>
    <div class="large-4 columns">
      <div class="block">
        <%= link_to year["year"], model_year_path(id: year["id"]), :class => "button large expand", :id => year["year"] %>
        <%= image_tag(get_sample_image_for_style(year["subModels"].first["styleIds"]), :class => "sample_image") %>
      </div>
    </div>
  <% end %>
</div>

app/views/model_years/show.html.erb
<div class="container">
  <h3>
    <%= link_to session[:condition].titleize, root_path %>
    <%= ":" %>
    <%= link_to "Makes", makes_path %>
    >
    <%= link_to @make, make_path(name: @make, id: @make_id) %>
    >
    <%= link_to @model, model_years_path(make: @make, model: @model, id: @model_id) %>
    >
    <%= @year %>
    >
    <%= "Styles" %>
  </h3>
</div>
<div class="row">
  <div class="large-6 columns">
    <%= image_tag(get_sample_image_for_style(@styles.first["subModels"].first["styleIds"])) %>
  </div>
</div>
<div class="row">
  <p></p>
  <% @styles.each do |style| %>
    <div class="large-6 columns">
      <%= link_to style_name(style), style_detail_path(id: style["id"]), :class => "button expand" %>
    </div>
  <% end %>
</div>